### ISSUE TITLE
[Enhancement] Enable site isolation on firefox

### ISSUE THREAD

**Issue by syeopite** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-Firefox-Configuration#1]
https://blog.mozilla.org/security/2021/05/18/introducing-site-isolation-in-firefox/

`fission.autostart = true`

**Comment by TheFrenchGhosty** [comment]
I never heard of it, I'll have to take a look, thanks :)

**Comment by TheFrenchGhosty** [comment]
Made irrelevant after the refactor: https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-Firefox-Configuration/commit/649a7d8cd8066a46ad338a5561bd5e40d36d846f

It's enabled by default on LibreWolf
